package main

var UpsertEventQuery string = `INSERT INTO earthquake.events (id, 
																				 time,
																				 coordinates, 
																				 updated, 
																				 depth,
																				 magnitude, 
																				 place, 
																				 tz, 
																				 url, 
																				 detail, 
																				 felt, 
																				 cdi, 
																				 mmi, 
																				 alert, 
																				 status, 
																				 significance, 
																				 network, 
																				 code, 
																				 ids, 
																				 sources, 
																				 types, 
																				 nst, 
																				 dmin, 
																				 rms, 
																				 gap, 
																				 magnitude_type, 
																				 type, 
																				 title, 
																				 dmin_distance) 
				  VALUES ($1, 
				  				$2,
				  				ST_MakePoint($3, $4), 
				  				$5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28, $29)
					ON CONFLICT (id, time)
					DO UPDATE SET
						coordinates = EXCLUDED.coordinates,
						updated = EXCLUDED.updated,
						depth = EXCLUDED.depth,
						magnitude = EXCLUDED.magnitude,
						place = EXCLUDED.place,
						tz = EXCLUDED.tz,
						url = EXCLUDED.url,
						detail = EXCLUDED.detail,
						felt = EXCLUDED.felt,
						cdi = EXCLUDED.cdi,
						mmi = EXCLUDED.mmi,
						alert = EXCLUDED.alert,
						status = EXCLUDED.status,
						significance = EXCLUDED.significance,
						network = EXCLUDED.network,
						code = EXCLUDED.code,
						ids = EXCLUDED.ids,
						sources = EXCLUDED.sources,
						types = EXCLUDED.types,
						nst = EXCLUDED.nst,
						dmin = EXCLUDED.dmin,
						rms = EXCLUDED.rms,
						gap = EXCLUDED.gap,
						magnitude_type = EXCLUDED.magnitude_type,
						type = EXCLUDED.type,
						title = EXCLUDED.title,
						dmin_distance = EXCLUDED.dmin_distance`
