apiVersion: apps/v1
kind: Deployment
metadata:
  name: fetcher-day
  namespace: earthquakes-app
  labels:
    run: fetcher-day
spec:
  replicas: 1
  selector:
    matchLabels:
      run: fetcher-day

  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate

  template:
    metadata:
      labels:
        run: fetcher-day
    spec:
      nodeSelector:
        kubernetes.io/hostname: arboretum
      containers:
        - image: localhost:5000/fetcher:latest
          imagePullPolicy: Always
          name: fetcher
          env:
            - name: NATS_URL
              value: "nats://nats:4222"
            - name: POLL_FREQUENCY
              value: "1h" # 30m, 1h, 6h etc.
            - name: FEED_FREQUENCY_TYPE
              value: "all_day"
            - name: PUB_SUBJECT
              value: "earthquakes.raw"
          resources:
            limits:
              cpu: "100m"
              memory: "64Mi"
            requests:
              cpu: "50m"
              memory: "32Mi"
      restartPolicy: Always
