apiVersion: apps/v1
kind: Deployment
metadata:
  name: fetcher
  namespace: earthquakes-app
  labels:
    run: fetcher
spec:
  replicas: 1
  selector:
    matchLabels:
      run: fetcher

  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate

  template:
    metadata:
      labels:
        run: fetcher
    spec:
      nodeSelector:
        kubernetes.io/hostname: arboretum
      containers:
        - image: localhost:5000/fetcher:latest
          imagePullPolicy: Always
          name: fetcher
          env:
            - name: NATS_URL
              value: "nats://nats:4222"
            - name: FEED_FREQUENCY_TYPE
              value: "all_hour"
            - name: PUB_SUBJECT
              value: "earthquakes.raw"
          resources:
            limits:
              cpu: "100m"
              memory: "64Mi"
            requests:
              cpu: "50m"
              memory: "32Mi"
      restartPolicy: Always
