apiVersion: v1
kind: Service
metadata:
  name: nats
  namespace: earthquakes-app
spec:
  type: ClusterIP
  selector:
    app: nats
  ports:
    - name: client
      port: 4222
    - name: monitor
      port: 8222
