apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nats
  namespace: earthquakes-app
spec:
  serviceName: nats
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
        - name: nats
          image: nats:2.12 # <=2.12.1 versions are prone to write loss and split-brain in JetStream mode!
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4222
              name: client
            - containerPort: 8222
              name: monitor
          args:
            - "-js"
            - "-m"
            - "8222"
            - "-sd"
            - "/data/jetstream"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - name: jetstream-data
              mountPath: /data/jetstream
  volumeClaimTemplates:
    - metadata:
        name: jetstream-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 50Mi
