apiVersion: apps/v1
kind: Deployment
metadata:
  name: transformer
  labels:
    run: transformer
spec:
  replicas: 1
  selector:
    matchLabels:
      run: transformer

  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate

  template:
    metadata:
      labels:
        run: transformer
    spec:
      nodeSelector:
        kubernetes.io/hostname: arboretum
      containers:
      - image: localhost:5000/transformer:latest
        imagePullPolicy: Always
        name: transformer
        env:
        - name: NATS_URL
          value: "nats://nats:4222"
        - name: SUB_SUBJECT
          value: "earthquakes.raw.all_hour"
        - name: PUB_SUBJECT
          value: "earthquakes.all_hour"

        resources:
          limits:
            cpu: "100m"
            memory: "64Mi"
          requests:
            cpu: "50m"
            memory: "32Mi"
        restartPolicy: Always


